spring.application.name=shipment-tracker
# Removed for production, but can be used for local development and testing
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password
# spring.h2.console.enabled=true

# psotgreSQL configuration for production
spring.datasource.url=jdbc:postgresql://postgres:5432/shipmentdb
spring.datasource.username=shipmentuser
spring.datasource.password=shipmentpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect